### PR TITLE
[Feat]: Added WatchLater

### PR DESCRIPTION
**Pull request by parthpandyappp**
### Features for User
- User can add videos to Watch Later (By clicking on WatchLater icon given below).
- User can remove videos from Watch Later.

### Tasks performed
- Created a `genericDataProvider` for providing `watchLater`, `History` & other data.
- Created `genericReducer` to handle the data for Reducer in `genericDataProvider`.
- Created `helper-functions` for enhancing the modularity of the code my extracting the pure functions in separate file.
- Updated Barrels

#### WatchLater Icon in the video page
watch-later

### CODE REVIEW

**Review by yashpatel1797 — APPROVED** [review]
code looks clean
file structure is good
design looks consistent

**Comment by parthpandyappp** [comment]
Thanks @yashpatel1797 for the PR review :+1:

**Review by sonishreyas — APPROVED** [review]
Code looks good and easy to understand.

**Comment by parthpandyappp** [comment]
Thanks for your valuable reviews :+1:

**Pull request merged**
